config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :categories
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :require_login

  # GET /categories
  # GET /categories.json
  def index
    session[:tab] = 'category'	  
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
	session[:tab] = 'home'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :require_login, except: ['index','show']

  # GET /posts
  # GET /posts.json
  def index
    @category_id = params[:category_id]
    session[:tab] = "post_#{@category_id}" 
    @posts =  Post.where(category_id: @category_id).all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @category_id = params[:category_id]
    @post = Post.new(category_id: @category_id)
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	#get categroies
	def categories
		Category.all
	end

	#sett active nav tab
	def active_nav tab
	  return session['tab'] == tab ?  'active' : ''
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :name ,:class => "form-control",:placeholder=>"Category Name", "required" => true, "autofocus" => true %>
  </div>


  <div class="actions">
              <%= form.submit(:class => "btn btn-sm btn-primary")%>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h5>Editing Category</h5>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h5>Post Categories</h5>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path ,:class => "btn btn-sm btn-outline-info" %>

app/views/categories/new.html.erb
<h5>New Category</h5>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/home/index.html.erb
<h4 class="pt-3">Welcome to My Blog</h4>
<div class="row pt-2">
	<div class="col-12">
		<h6>	Post group by day </h6>
	</div>	
	<div class="col-12">
		<%= line_chart Post.group("date(created_at)").count %>
	</div>	
</div>


<div class="row pt-2">
        <div class="col-12">
		<h6>	Post group by category </h6>
        </div>
        <div class="col-12">
		<%= pie_chart Post.joins(:category).group('categories.name').count %>
        </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Blog</title>
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>

		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>

	<body>
		<nav class="navbar navbar-expand-lg navbar-dark bg-info fixed-top">
			<%= link_to 'My Blog', root_path,:class => "navbar-brand" %>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item <%= active_nav('home')%>">
						<a class="nav-link" href="<%=root_path%>">Home <span class="sr-only">(current)</span></a>
					</li>
					<% categories.each do |category|%>
						<li class="nav-item <%= active_nav("post_#{category.id}")%>">
							<%=link_to category.name,posts_path(:category_id => category.id),:class => "nav-link"%>
						</li>
					<%end%>
					<% if signed_in? %>
						<li class="nav-item <%= active_nav('category')%>">
							<%= link_to 'Setting', categories_path,:class => "nav-link" %>
						</li>
					<% end %>
				</ul>
				<form class="form-inline my-2 my-lg-0">
					<% if signed_in? %>
						<%= current_user.email %> &nbsp;
						<%= link_to "Sign out", sign_out_path, method: :delete,class: "btn btn-light" %>
					<% else %>
						<%= link_to "Sign in", sign_in_path,class: "btn btn-light" %>
					<% end %>
				</form>
			</div>
		</nav>

		<main>
		<div class="container mt-5">
			<div class="main">	
				<%= yield %>
			</div>
		</div>
		</main>


	</body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
    <%= form.hidden_field :category_id %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title,:class => "form-control" %>
  </div>

   <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body,:class => "form-control",:rows => 16 %>
  </div>

  <div class="actions">
	  <%= form.submit(:class => "btn btn-primary")%>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h5>Editing Post</h5>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path(category_id: @post.category_id) %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h5>Posts List</h5>

<table class="table table-striped">
  <thead>
    <tr>
      <th width="20%">Title</th>
      <th width="50%">Body</th>
      <th>Update at</th>
	<% if signed_in? %>
      		<th colspan="2"></th>
	<%end%>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, post %></td>
        <td><%= post.body.truncate(100) %></td>
        <td><%= post.updated_at %></td>
	<% if signed_in? %>
        	<td><%= link_to 'Edit', edit_post_path(post) %></td>
        	<td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<% if signed_in? %>
	<br>
	<%= link_to 'New Post', new_post_path(category_id: @category_id),:class => "btn btn-sm btn-outline-info" %>
<%end%>

app/views/posts/new.html.erb
<h5>New Post</h5>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path(category_id: @category_id) %>

app/views/posts/show.html.erb
<h4 class="pt-4">
  <%= @post.title %>
</h4>

<p class="pt-1">
  <%=simple_format @post.body %>
</p>


<%= link_to 'Back', posts_path(category_id: @post.category_id),:class => "btn btn-sm btn-outline-info"%>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>